 function tableout = importDatFile(filename ) 
%% Import data from text file.
% Script for importing data from the following text file: WACH_B* .dat
% files

% Auto-generated by MATLAB on 2017/07/07 15:44:34
% 7/7/17 Now includes DO percent saturation and ProfileID

%% Initialize variables.
delimiter = ',';
startRow = 5;

%% Format for each line of text:
%   column1: datetimes (%{yyyy-MM-dd HH:mm:ss}D)
%	column3: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
% For more information, see the TEXTSCAN documentation.
% formatSpec = '%q%*q%*q%*q%f%f%f%*q%*q%f%f%f%f%f%*q%f%*s%*s%[^\n\r]';
% {yyyy-MM-dd HH:mm:ss}
formatSpec = '%q%*q%f%*q%f%f%f%*q%*q%f%f%f%f%f%f%f%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
tableout = table(dataArray{1:end-1}, 'VariableNames', {'DateTime','ProfileID','Depth','Temperature','Conductivity','pH','ORP','Turbidity','Chlorophyll','BGAlgae','PercentDO','DO'});
